---
- name: Setup workstation
  hosts:
    - wall-e
  connection: local
  tasks:
    - name: Add Visual Studio Code repo
      become: true
      ansible.builtin.copy:
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/yum.repos.d/vscode.repo
        mode: u=rw,g=r,o=r

    - name: Add Dropbox repo
      become: true
      ansible.builtin.copy:
        content: |
          [Dropbox]
          name=Dropbox Repository
          baseurl=http://linux.dropbox.com/fedora/$releasever/
          gpgkey=https://linux.dropbox.com/fedora/rpm-public-key.asc
        dest: /etc/yum.repos.d/dropbox.repo
        mode: u=rw,g=r,o=r

    - name: Add Tailscale repo
      become: true
      ansible.builtin.copy:
        content: |
          [tailscale-stable]
          name=Tailscale stable
          baseurl=https://pkgs.tailscale.com/stable/fedora/$basearch
          enabled=1
          type=rpm
          repo_gpgcheck=1
          gpgcheck=0
          gpgkey=https://pkgs.tailscale.com/stable/fedora/repo.gpg
        dest: /etc/yum.repos.d/tailscale.repo
        mode: u=rw,g=r,o=r

    - name: Overlay packages
      community.general.rpm_ostree_pkg:
        name:
          - code
          - fish
          - nautilus-dropbox
          - podman-docker
          - restic
          - tailscale
        state: present

    - name: Change shell to fish
      become: true
      ansible.builtin.user:
        name: fernando
        shell: /usr/bin/fish

    - name: Add Flathub repo
      become: true
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Disable Fedora flatpak repo
      become: true
      community.general.flatpak_remote:
        name: fedora
        state: present
        enabled: false

    - name: Install flatpaks
      community.general.flatpak:
        name:
          - ca.desrt.dconf-editor
          - com.calibre_ebook.calibre
          - com.github.jeromerobert.pdfarranger
          - com.github.tchx84.Flatseal
          - com.github.unrud.VideoDownloader
          - com.google.Chrome
          - com.makemkv.MakeMKV
          - com.mattjakeman.ExtensionManager
          - com.spotify.Client
          - com.transmissionbt.Transmission
          - com.valvesoftware.Steam
          - fr.handbrake.ghb
          - io.github.fsobolev.TimeSwitch
          - org.bunkus.mkvtoolnix-gui
          - org.gimp.GIMP
          - org.gnome.baobab
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.clocks
          - org.gnome.Evince
          - org.gnome.font-viewer
          - org.gnome.gitlab.YaLTeR.Identity
          - org.gnome.Logs
          - org.gnome.Loupe
          - org.gnome.NautilusPreviewer
          - org.gnome.TextEditor
          - org.inkscape.Inkscape
          - org.jdownloader.JDownloader
          - org.libreoffice.LibreOffice
          - org.mozilla.firefox
          - org.videolan.VLC
          - org.zotero.Zotero
        state: present
        remote: flathub

    - name: Pull texlive/texlive image
      containers.podman.podman_image:
        name: "docker.io/texlive/texlive:latest"
        state: present

    - name: Pull my toolbox image
      containers.podman.podman_image:
        name: "ghcr.io/fmhahne/fedora-toolbox:latest"
        state: present
