---
- hosts:
    - wall-e
    - oscillon
  connection: local
  tasks:
    - name: Add Visual Studio Code repo
      become: true
      ansible.builtin.copy:
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/yum.repos.d/vscode.repo
        mode: u=rw,g=r,o=r

    - name: Add Dropbox repo
      become: true
      ansible.builtin.copy:
        content: |
          [Dropbox]
          name=Dropbox Repository
          baseurl=http://linux.dropbox.com/fedora/$releasever/
          gpgkey=https://linux.dropbox.com/fedora/rpm-public-key.asc
        dest: /etc/yum.repos.d/dropbox.repo
        mode: u=rw,g=r,o=r

    - name: Add Google Chrome repo
      become: true
      ansible.builtin.copy:
        content: |
          [google-chrome]
          name=google-chrome
          baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
          skip_if_unavailable=True
          gpgcheck=1
          gpgkey=https://dl.google.com/linux/linux_signing_key.pub
          enabled=1
        dest: /etc/yum.repos.d/google-chrome.repo
        mode: u=rw,g=r,o=r

    - name: Overlay packages
      community.general.rpm_ostree_pkg:
        name:
          - code
          - fish
          - google-chrome-stable
          - nautilus-dropbox
          - podman-docker
          - rclone
          - restic
          - syncthing
        state: present

    - name: Change shell to fish
      become: true
      ansible.builtin.user:
        name: fernando
        shell: /usr/bin/fish

    - name: Add Flathub repo
      become: true
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Disable Fedora flatpak repo
      become: true
      community.general.flatpak_remote:
        name: fedora
        state: present
        enabled: false

    - name: Install flatpaks
      community.general.flatpak:
        name:
          - com.github.jeromerobert.pdfarranger
          - com.github.tchx84.Flatseal
          - com.spotify.Client
          - org.gnome.baobab
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.clocks
          - org.gnome.eog
          - org.gnome.Evince
          - org.gnome.font-viewer
          - org.gnome.Logs
          - org.gnome.NautilusPreviewer
          - org.gnome.TextEditor
          - org.libreoffice.LibreOffice
          - org.videolan.VLC
          - org.zotero.Zotero
        state: present
        remote: flathub

    - name: Pull texlive/texlive image
      containers.podman.podman_image:
        name: "docker.io/texlive/texlive:latest"
        state: present

    - name: Install PyPI packages
      ansible.builtin.pip:
        name:
          - ansible
          - pip
          - tvnamer
        state: latest
        extra_args: --user

- hosts:
    - wall-e
  connection: local
  tasks:
    - name: Install flatpaks
      community.general.flatpak:
        name:
          - com.calibre_ebook.calibre
          - com.github.unrud.VideoDownloader
          - com.makemkv.MakeMKV
          - com.transmissionbt.Transmission
          - com.valvesoftware.Steam
          - fr.handbrake.ghb
          - org.bunkus.mkvtoolnix-gui
          - org.mozilla.firefox
        state: present
        remote: flathub
