---
- hosts:
    - wall-e
    - oscillon
  connection: local
  roles:
    - rpm-ostree-upgrades
  tasks:
    - name: Add Visual Studio Code repo
      become: true
      ansible.builtin.copy:
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/yum.repos.d/vscode.repo
        mode: u=rw,g=r,o=r

    - name: Add Dropbox repo
      become: true
      ansible.builtin.copy:
        content: |
          [Dropbox]
          name=Dropbox Repository
          baseurl=http://linux.dropbox.com/fedora/35/
          gpgkey=https://linux.dropbox.com/fedora/rpm-public-key.asc
        dest: /etc/yum.repos.d/dropbox.repo
        mode: u=rw,g=r,o=r

    - name: Overlay packages
      community.general.rpm_ostree_pkg:
        name:
          - code
          - fish
          - nautilus-dropbox
          - podman-docker
          - rclone
          - restic
        state: present

    - name: Remove RPM Firefox
      ansible.builtin.command: rpm-ostree override remove firefox
      register: result
      changed_when: result.rc == 0
      failed_when: false

    - name: Add Flathub repo
      become: true
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install flatpaks
      community.general.flatpak:
        name:
          - com.spotify.Client
          - org.gnome.baobab
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.eog
          - org.gnome.Evince
          - org.gnome.font-viewer
          - org.gnome.Logs
          - org.gnome.TextEditor
          - org.libreoffice.LibreOffice
          - org.mozilla.firefox
          - org.videolan.VLC
          - org.zotero.Zotero
        state: present
        remote: flathub

    - name: Install ffmpeg
      become: true
      community.general.flatpak:
        name: org.freedesktop.Platform.ffmpeg-full/x86_64/21.08
        state: present
        remote: flathub

    - name: Pull texlive/texlive image
      containers.podman.podman_image:
        name: "docker.io/texlive/texlive:latest"
        state: present

    - name: Install PyPI packages
      ansible.builtin.pip:
        name:
          - black
          - isort
          - matplotlib
          - mypy
          - numpy
          - pandas
          - pip
          - pylint
          - pytest
          - scipy
        state: latest
        extra_args: --user

- hosts: wall-e
  connection: local
  tasks:
    - name: Install Flatpaks
      community.general.flatpak:
        name:
          - com.calibre_ebook.calibre
          - com.transmissionbt.Transmission
          - org.bunkus.mkvtoolnix-gui
          - org.gnome.clocks
          - org.gnucash.GnuCash
        state: present
        remote: flathub

    - name: Install PyPI packages
      ansible.builtin.pip:
        name: tvnamer
        state: latest
        extra_args: --user
