---
- name: Reload rpm-ostree configuration
  become: true
  ansible.builtin.command:
    cmd: rpm-ostree reload

- name: Enable rpm-ostree-automatic.timer
  become: true
  ansible.builtin.systemd:
    name: rpm-ostreed-automatic.timer
    state: started
    enabled: true
    daemon_reload: true
