---
- name: Automatically stage upgrades
  become: true
  ansible.builtin.lineinfile:
    path: /etc/rpm-ostreed.conf
    regexp: ^#AutomaticUpdatePolicy=none
    line: AutomaticUpdatePolicy=stage
  notify:
    - Reload rpm-ostree configuration
    - Enable rpm-ostree-automatic.timer
